# Generated by Django 5.0.14 on 2026-08-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='ministries.group'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['branch', 'publish_at'], name='communicati_branch__b92bdb_idx'),
        ),
    ]
