# Generated by Django 5.0.14 on 2026-08-30 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
        ('members', '0003_member_college_member_community_member_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience_type',
            field=models.CharField(choices=[('EVERYONE', 'Everyone in the branch'), ('FELLOWSHIP', 'Fellowship'), ('UNIT', 'Unit'), ('MINISTRY', 'Ministry/Group'), ('STAFF_COMMUNITY', 'Staff Community'), ('CUSTOM', 'Custom (explicit groups/statuses)')], default='CUSTOM', help_text='Phase 10 default is CUSTOM so existing rows/callers that only ever set target_groups/target_membership_statuses keep working unchanged.', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='channels',
            field=models.JSONField(blank=True, default=list, help_text="List of notifications.NotificationChannel values, e.g. ['EMAIL', 'SMS']. Empty is treated as ['EMAIL'] for backward compatibility with rows created before this field existed."),
        ),
        migrations.AddField(
            model_name='announcement',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='sending_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_community',
            field=models.CharField(blank=True, help_text='members.CommunityClassification value, set when audience_type=STAFF_COMMUNITY.', max_length=10),
        ),
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('announcements_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preference', to='members.member')),
            ],
            options={
                'db_table': 'communications_preference',
            },
        ),
    ]
