import type { Permission, Role, User } from "../types/domain";

const rolePermissions: Record<Role, Permission[]> = {
  super_admin: [
    "dashboard:view",
    "members:read",
    "members:write",
    "attendance:read",
    "attendance:write",
    "attendance:scan",
    "attendance:manual",
    "events:read",
    "events:write",
    "finance:read",
    "finance:write",
    "communication:write",
    "workers:read",
    "workers:write",
    "workers:acknowledge",
    "assets:read",
    "assets:write",
    "media:write",
    "cms:write",
    "analytics:read",
    "branches:manage",
    "audit:read",
    "settings:manage",
    "community:view",
    "community:view_all",
    "community:manage",
    "leadership:view",
    "leadership:manage",
    "chapel:announce",
  ],
  chapel_admin: [
    "dashboard:view",
    "members:read",
    "members:write",
    "attendance:read",
    "attendance:write",
    "attendance:scan",
    "attendance:manual",
    "events:read",
    "events:write",
    "finance:read",
    "finance:write",
    "communication:write",
    "workers:read",
    "workers:write",
    "workers:acknowledge",
    "assets:read",
    "assets:write",
    "media:write",
    "cms:write",
    "analytics:read",
    "audit:read",
    "community:view",
    "community:view_all",
    "community:manage",
    "leadership:view",
    "leadership:manage",
    "chapel:announce",
  ],
  chaplain: [
    "dashboard:view",
    "members:read",
    "attendance:read",
    "events:read",
    "events:write",
    "communication:write",
    "analytics:read",
    "community:view",
    "community:view_all",
    "leadership:view",
    "chapel:announce",
  ],
  student_chaplain: [
    "dashboard:view",
    "members:read",
    "attendance:read",
    "events:read",
    "events:write",
    "communication:write",
    "community:view",
    "community:view_all",
    "leadership:view",
    "chapel:announce",
  ],
  treasurer: [
    "dashboard:view",
    "attendance:read",
    "events:read",
    "finance:read",
    "finance:write",
    "community:view",
    "leadership:view",
  ],
  chapel_official: [
    "dashboard:view",
    "members:read",
    "attendance:read",
    "events:read",
    "community:view",
    "leadership:view",
  ],
  pastor: [
    "dashboard:view",
    "members:read",
    "attendance:read",
    "events:read",
    "events:write",
    "workers:read",
    "analytics:read",
    "media:write",
    "community:view",
    "community:view_all",
    "leadership:view",
  ],
  worker: [
    "dashboard:view",
    "attendance:read",
    "events:read",
    "workers:read",
    "workers:acknowledge",
    "community:view",
  ],
  attendance_usher: ["attendance:read", "attendance:scan", "attendance:manual"],
  member: [
    "dashboard:view",
    "attendance:read",
    "events:read",
    "community:view",
  ],
};

export function hasPermission(user: User | null, permission?: Permission) {
  return !permission || Boolean(user?.permissions.includes(permission));
}

export function buildDemoUser(role: Role): User {
  const names: Record<Role, string> = {
    super_admin: "Dr. Tola Adebayo",
    chapel_admin: "Grace Adeyemi",
    chaplain: "Chaplain Emmanuel Adekunle",
    student_chaplain: "Akintobi Oluwabori Favour",
    treasurer: "Olutanwa Esther",
    chapel_official: "Chapel Official",
    pastor: "Pastor Daniel Eze",
    worker: "Moyo Bello",
    attendance_usher: "Attendance Usher 01",
    member: "Favour Okafor",
  };
  const name = names[role];
  return {
    id: `demo-${role}`,
    name,
    email: `${name.toLowerCase().replaceAll(" ", ".")}@example.edu.ng`,
    role,
    roles: [role],
    branchId: "abeokuta-main",
    branchName: "Abeokuta Main Chapel",
    permissions: rolePermissions[role],
    initials: name
      .split(" ")
      .slice(0, 2)
      .map((part) => part[0])
      .join(""),
  };
}
