# Generated by Django 5.0.14 on 2026-08-22 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('FINANCIAL_ACTION', 'Financial Action'), ('MEMBER_RECORD_ACCESS', 'Member Record Access')], max_length=30)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_log_resourc_2570dd_idx'), models.Index(fields=['user', '-created_at'], name='audit_log_user_id_b57afc_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx')],
            },
        ),
    ]
