# Generated by Django 5.0.14 on 2026-08-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('FINANCIAL_ACTION', 'Financial Action'), ('MEMBER_RECORD_ACCESS', 'Member Record Access'), ('MEMBER_DEACTIVATE', 'Member Deactivate'), ('MEMBER_REACTIVATE', 'Member Reactivate'), ('MEMBER_MERGE', 'Member Merge'), ('MEMBER_SELF_REGISTER', 'Member Self Registration'), ('VISITOR_FOLLOW_UP', 'Visitor Follow Up'), ('BRANCH_CHANGE', 'Branch Change'), ('EVENT_CHANGE', 'Event Change'), ('COMMUNICATION_ACTION', 'Communication Action'), ('MFA_ENROLL', 'MFA Enroll'), ('MFA_ENABLE', 'MFA Enable'), ('MFA_RESET', 'MFA Administrative Reset')], max_length=30),
        ),
    ]
