# Generated by Django 5.0.14 on 2026-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('FINANCIAL_ACTION', 'Financial Action'), ('FINANCIAL_RECORD_VOIDED', 'Financial Record Voided'), ('FINANCIAL_RECORD_REFUNDED', 'Financial Record Refunded'), ('MEMBER_RECORD_ACCESS', 'Member Record Access'), ('MEMBER_DEACTIVATE', 'Member Deactivate'), ('MEMBER_REACTIVATE', 'Member Reactivate'), ('MEMBER_MERGE', 'Member Merge'), ('MEMBER_TRANSFER', 'Member Transfer'), ('GROUP_LEADERSHIP_CHANGE', 'Group Leadership Change'), ('MEMBER_SELF_REGISTER', 'Member Self Registration'), ('VISITOR_FOLLOW_UP', 'Visitor Follow Up'), ('BRANCH_CHANGE', 'Branch Change'), ('EVENT_CHANGE', 'Event Change'), ('COMMUNICATION_ACTION', 'Communication Action'), ('MFA_ENROLL', 'MFA Enroll'), ('MFA_ENABLE', 'MFA Enable'), ('MFA_RESET', 'MFA Administrative Reset'), ('PASTORAL_CASE_CREATE', 'Pastoral Case Create'), ('PASTORAL_CASE_ASSIGN', 'Pastoral Case Assign'), ('PASTORAL_CASE_STATUS_CHANGE', 'Pastoral Case Status Change'), ('PASTORAL_CASE_ESCALATE', 'Pastoral Case Escalate'), ('PASTORAL_CASE_CLOSE', 'Pastoral Case Close'), ('PASTORAL_CASE_ACCESS', 'Pastoral Case Access'), ('PASTORAL_NOTE_CREATE', 'Pastoral Note Create'), ('PRAYER_REQUEST_CREATE', 'Prayer Request Create'), ('PRAYER_REQUEST_ASSIGN', 'Prayer Request Assign'), ('PRAYER_REQUEST_STATUS_CHANGE', 'Prayer Request Status Change'), ('PRAYER_REQUEST_CLOSE', 'Prayer Request Close'), ('PRAYER_REQUEST_ACCESS', 'Prayer Request Access'), ('PRAYER_NOTE_CREATE', 'Prayer Note Create'), ('FINANCIAL_PERIOD_CLOSED', 'Financial Period Closed'), ('FINANCIAL_PERIOD_LOCKED', 'Financial Period Locked'), ('FINANCIAL_PERIOD_REOPENED', 'Financial Period Reopened'), ('RECONCILIATION_CREATED', 'Reconciliation Created'), ('RECONCILIATION_STARTED', 'Reconciliation Started'), ('RECONCILIATION_COMPLETED', 'Reconciliation Completed'), ('RECONCILIATION_APPROVED', 'Reconciliation Approved'), ('ADJUSTMENT_CREATED', 'Financial Adjustment Created'), ('ADJUSTMENT_APPROVED', 'Financial Adjustment Approved'), ('ADJUSTMENT_REJECTED', 'Financial Adjustment Rejected'), ('ADJUSTMENT_APPLIED', 'Financial Adjustment Applied')], max_length=30),
        ),
    ]
