import uuid

from django.db import models


class RecurrenceFrequency(models.TextChoices):
    NONE = "NONE", "Does not repeat"
    DAILY = "DAILY", "Daily"
    WEEKLY = "WEEKLY", "Weekly"
    MONTHLY = "MONTHLY", "Monthly"
    YEARLY = "YEARLY", "Yearly"


class Location(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    branch = models.ForeignKey("organizations.Branch", on_delete=models.CASCADE, related_name="locations")
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=500, blank=True)
    capacity = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        db_table = "events_location"

    def __str__(self):
        return self.name


class EventType(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=255, blank=True)

    class Meta:
        db_table = "events_event_type"

    def __str__(self):
        return self.name


class Event(models.Model):
    """
    A church service or event. Recurrence is modeled via `frequency` +
    `recurrence_end_date`; concrete occurrences are materialized as
    EventSchedule rows (generated by services.generate_event_schedules)
    so attendance/registration can point at a specific occurrence.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    branch = models.ForeignKey("organizations.Branch", on_delete=models.CASCADE, related_name="events")
    event_type = models.ForeignKey(EventType, null=True, blank=True, on_delete=models.SET_NULL, related_name="events")
    location = models.ForeignKey(Location, null=True, blank=True, on_delete=models.SET_NULL, related_name="events")

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    frequency = models.CharField(max_length=10, choices=RecurrenceFrequency.choices, default=RecurrenceFrequency.NONE)
    recurrence_end_date = models.DateField(null=True, blank=True)

    is_public = models.BooleanField(default=True)
    requires_registration = models.BooleanField(default=False)
    capacity = models.PositiveIntegerField(null=True, blank=True)
    registration_deadline = models.DateTimeField(
        null=True, blank=True,
        help_text="Spec Phase 7: registration deadline. If set, no new registration "
                   "(CONFIRMED or WAITLISTED) is accepted after this moment.",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "events_event"
        indexes = [models.Index(fields=["branch", "start_time"])]

    def __str__(self):
        return self.title


class EventSchedule(models.Model):
    """A single concrete occurrence of an Event (esp. for recurring events)."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="schedules")
    occurrence_start = models.DateTimeField()
    occurrence_end = models.DateTimeField()
    is_cancelled = models.BooleanField(default=False)

    class Meta:
        db_table = "events_schedule"
        indexes = [models.Index(fields=["event", "occurrence_start"])]
        unique_together = ("event", "occurrence_start")

    def __str__(self):
        return f"{self.event.title} @ {self.occurrence_start}"


class EventRegistrationStatus(models.TextChoices):
    """Spec Phase 7: capacity/waitlist/cancellation for event registration."""
    CONFIRMED = "CONFIRMED", "Confirmed"
    WAITLISTED = "WAITLISTED", "Waitlisted"
    CANCELLED = "CANCELLED", "Cancelled"


class EventRegistration(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    schedule = models.ForeignKey(EventSchedule, on_delete=models.CASCADE, related_name="registrations")
    member = models.ForeignKey("members.Member", on_delete=models.CASCADE, related_name="event_registrations")
    status = models.CharField(
        max_length=10, choices=EventRegistrationStatus.choices, default=EventRegistrationStatus.CONFIRMED,
    )
    registered_at = models.DateTimeField(auto_now_add=True)
    cancelled_at = models.DateTimeField(null=True, blank=True)
    attended = models.BooleanField(default=False)

    class Meta:
        db_table = "events_registration"
        # NOTE: deliberately still (schedule, member) even with a status
        # field -- see services.register_for_event, which reactivates an
        # existing CANCELLED row for a re-registration rather than
        # inserting a second one. A member should never hold two
        # registration rows for the same occurrence, cancelled or not;
        # that would make "did I already register" ambiguous.
        unique_together = ("schedule", "member")
        indexes = [models.Index(fields=["schedule", "status"])]


class EventReminder(models.Model):
    schedule = models.ForeignKey(EventSchedule, on_delete=models.CASCADE, related_name="reminders")
    send_at = models.DateTimeField()
    sent = models.BooleanField(default=False)
    channel = models.CharField(
        max_length=10, choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("PUSH", "Push")], default="EMAIL"
    )

    class Meta:
        db_table = "events_reminder"
