# Generated by Django 5.0.14 on 2026-08-22 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giving',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_records', to='members.member'),
        ),
        migrations.AddField(
            model_name='giving',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giving',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giving_records', to='finance.givingcategory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.member'),
        ),
        migrations.AddField(
            model_name='giving',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_record', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='finance.givingcategory'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='members.member'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='reconciled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_reference'], name='finance_pay_provide_9bd7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='giving',
            index=models.Index(fields=['branch', 'given_at'], name='finance_giv_branch__34fb92_idx'),
        ),
        migrations.AddIndex(
            model_name='giving',
            index=models.Index(fields=['member', 'category'], name='finance_giv_member__e4cc56_idx'),
        ),
    ]
