# Generated by Django 5.0.14 on 2026-08-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giving',
            options={'ordering': ['-given_at']},
        ),
    ]
