# Generated by Django 5.0.14 on 2026-09-04 06:13

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_registration_deadline_and_more'),
        ('finance', '0003_alter_giving_options'),
        ('members', '0004_engagementmetrics_memberfollowup'),
        ('ministries', '0004_alter_group_leader'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(help_text="Type of adjustment (e.g., 'Amount Correction', 'Category Change', 'Date Correction')", max_length=100)),
                ('field_name', models.CharField(blank=True, help_text="Field being adjusted (e.g., 'amount', 'category', 'given_at')", max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Original value before adjustment (JSON or string representation)')),
                ('new_value', models.TextField(blank=True, help_text='New value after adjustment (JSON or string representation)')),
                ('amount_delta', models.DecimalField(blank=True, decimal_places=2, help_text='Amount change (positive or negative) if applicable', max_digits=14, null=True)),
                ('reason', models.TextField(help_text='Detailed explanation of why this adjustment is necessary')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Approval status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When adjustment was created')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When adjustment was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('applied_at', models.DateTimeField(blank=True, help_text='When adjustment was actually applied to the system', null=True)),
            ],
            options={
                'db_table': 'finance_adjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'January 2026', 'Q1 2026'", max_length=100)),
                ('period_start', models.DateField(help_text='First day of period (inclusive)')),
                ('period_end', models.DateField(help_text='Last day of period (inclusive)')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked (Immutable)')], default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When period was closed', null=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='When period was locked (post-reconciliation)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_period',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED_PAYMENT', 'Unmatched Payment'), ('UNMATCHED_GIVING', 'Unmatched Giving'), ('AMOUNT_MISMATCH', 'Amount Mismatch')], help_text='Type of result entry', max_length=20)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Expected amount (from system/giving)', max_digits=14, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount (from bank/payment)', max_digits=14, null=True)),
                ('difference', models.DecimalField(decimal_places=2, default=0, help_text='Difference (expected - actual)', max_digits=14)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or resolution details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_reconciliation_result',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount (may be partial)', max_digits=14)),
                ('reason', models.CharField(max_length=500)),
                ('refunded_at', models.DateTimeField(auto_now_add=True)),
                ('payment_refund_reference', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'finance_refund',
            },
        ),
        migrations.AlterModelOptions(
            name='reconciliation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='giving',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional: Event-specific contribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_records', to='events.event'),
        ),
        migrations.AddField(
            model_name='giving',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional: Group/Fellowship/Unit-specific contribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_records', to='ministries.group'),
        ),
        migrations.AddField(
            model_name='giving',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('VOIDED', 'Voided')], default='CONFIRMED', max_length=15),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When discrepancy was approved', null=True),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved discrepancy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 4, 6, 13, 56, 698132, tzinfo=datetime.timezone.utc), help_text='When reconciliation was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='created_by',
            field=models.ForeignKey(help_text='User who initiated reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated difference (system_total - bank_total)', max_digits=16),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RECONCILED', 'Reconciled (Matched)'), ('DISCREPANCY', 'Discrepancy Found'), ('APPROVED', 'Approved (Discrepancy Resolved)')], default='PENDING', help_text='Current reconciliation status', max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='bank_total',
            field=models.DecimalField(decimal_places=2, help_text='Total from bank/gateway', max_digits=16),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='discrepancy_note',
            field=models.TextField(blank=True, help_text='Explanation of discrepancies or resolution notes'),
        ),
        # Was AlterField(bigint -> uuid) as auto-generated, but Postgres
        # can't cast bigint to uuid even with an empty table — see the
        # RolePermission id migration in accounts/0005 for the same issue.
        # No real data exists in this table yet, so drop+recreate is safe.
        migrations.RemoveField(
            model_name='reconciliation',
            name='id',
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='period_end',
            field=models.DateField(help_text='End date of reconciliation period (inclusive)'),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='period_start',
            field=models.DateField(help_text='Start date of reconciliation period (inclusive)'),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, help_text='When reconciliation was completed', null=True),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, help_text='User who completed reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='system_total',
            field=models.DecimalField(decimal_places=2, help_text='Total from system (Giving records)', max_digits=16),
        ),
        migrations.AlterUniqueTogether(
            name='reconciliation',
            unique_together={('branch', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='giving',
            index=models.Index(fields=['event'], name='finance_giv_event_i_f9fe5b_idx'),
        ),
        migrations.AddIndex(
            model_name='giving',
            index=models.Index(fields=['group'], name='finance_giv_group_i_24a2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='giving',
            index=models.Index(fields=['status'], name='finance_giv_status_f4a806_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['branch', 'status'], name='finance_rec_branch__d8d480_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['period_start', 'period_end'], name='finance_rec_period__fb6847_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['status', 'created_at'], name='finance_rec_status_209d7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='giving',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='finance_giving_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='finance_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='pledge',
            constraint=models.CheckConstraint(check=models.Q(('amount_pledged__gt', 0)), name='finance_pledge_amount_pledged_positive'),
        ),
        migrations.AddConstraint(
            model_name='pledge',
            constraint=models.CheckConstraint(check=models.Q(('amount_fulfilled__gte', 0), ('amount_fulfilled__lte', models.F('amount_pledged'))), name='finance_pledge_amount_fulfilled_valid'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='branch',
            field=models.ForeignKey(help_text='Branch where adjustment applies', on_delete=django.db.models.deletion.PROTECT, related_name='financial_adjustments', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_adjustments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='giving',
            field=models.ForeignKey(blank=True, help_text='Giving record being adjusted (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='finance.giving'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Payment record being adjusted (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved/rejected the adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_adjustments_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialperiod',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_periods', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='financialperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='User who closed this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_financial_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User who locked this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_financial_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='financial_period',
            field=models.ForeignKey(blank=True, help_text='Period being adjusted (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='finance.financialperiod'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='giving',
            field=models.ForeignKey(blank=True, help_text='Giving record (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_results', to='finance.giving'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Payment record (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_results', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='reconciliation',
            field=models.ForeignKey(help_text='Parent reconciliation', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='finance.reconciliation'),
        ),
        migrations.AddField(
            model_name='refund',
            name='original_giving',
            field=models.ForeignKey(help_text='The original giving record being refunded', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.giving'),
        ),
        migrations.AddField(
            model_name='refund',
            name='refunded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financialperiod',
            index=models.Index(fields=['branch', 'status'], name='finance_per_branch__d82cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='financialperiod',
            index=models.Index(fields=['period_start', 'period_end'], name='finance_per_period__ad557f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialperiod',
            unique_together={('branch', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='financialadjustment',
            index=models.Index(fields=['branch', 'status'], name='finance_adj_branch__f98038_idx'),
        ),
        migrations.AddIndex(
            model_name='financialadjustment',
            index=models.Index(fields=['financial_period'], name='finance_adj_financi_efa9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='financialadjustment',
            index=models.Index(fields=['giving'], name='finance_adj_giving__fb0245_idx'),
        ),
        migrations.AddIndex(
            model_name='financialadjustment',
            index=models.Index(fields=['payment'], name='finance_adj_payment_572c49_idx'),
        ),
        migrations.AddIndex(
            model_name='financialadjustment',
            index=models.Index(fields=['status', 'created_at'], name='finance_adj_status_2e7e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['reconciliation', 'result_type'], name='finance_rec_reconci_30ace5_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['payment'], name='finance_rec_payment_7cb8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['giving'], name='finance_rec_giving__83d090_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['original_giving', 'refunded_at'], name='finance_ref_origina_69078e_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='finance_refund_amount_positive'),
        ),
    ]
