# Generated by Django 5.2.17 on 2026-09-18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_financialadjustment_financialperiod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reconciliation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
