# Generated by Django 5.2.17 on 2026-09-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_standard_online_giving_categories(apps, schema_editor):
    GivingCategory = apps.get_model("finance", "GivingCategory")
    for name, description in (
        ("Offering", "General offering given through ChapelFlow."),
        ("Tithe", "Tithe given through ChapelFlow."),
    ):
        GivingCategory.objects.get_or_create(
            name=name,
            defaults={"description": description, "is_active": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0005_alter_reconciliation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="giving_category",
            field=models.ForeignKey(
                blank=True,
                help_text="The purpose selected before the gateway checkout.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_attempts",
                to="finance.givingcategory",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="giving_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="payment",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated account that started the gateway checkout.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(create_standard_online_giving_categories, migrations.RunPython.noop),
    ]
