# Generated by Django 5.0.14 on 2026-08-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerassignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='volunteerprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
