# Generated by Django 5.0.14 on 2026-08-30 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_registration_deadline_and_more'),
        ('ministries', '0004_alter_group_leader'),
        ('volunteers', '0002_phase1_default_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=False, help_text="False (default) = this is an UNAVAILABLE window (the common case people record: 'busy Tuesday evenings'). True = an explicit availability window, used only if the volunteer has opted into whitelist-style availability.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'volunteers_availability',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_assignments', to='ministries.group'),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='hours_logged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending onboarding'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Phase 9 onboarding lifecycle. Defaults to ACTIVE so existing rows and call sites that never set this stay behaviorally unchanged.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='volunteerassignment',
            index=models.Index(fields=['volunteer', 'status'], name='volunteers__volunte_3e63ad_idx'),
        ),
        migrations.AddField(
            model_name='volunteeravailability',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='volunteers.volunteerprofile'),
        ),
        migrations.AddIndex(
            model_name='volunteeravailability',
            index=models.Index(fields=['volunteer', 'weekday'], name='volunteers__volunte_a9671d_idx'),
        ),
    ]
