# Generated by Django 5.0.14 on 2026-08-26 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_member_college_member_community_member_department_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('how_heard', models.CharField(blank=True, max_length=255)),
                ('first_visit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('FOLLOWED_UP', 'Followed Up'), ('REGISTERED', 'Registered as Member'), ('LAPSED', 'Lapsed (no further contact)')], default='NEW', max_length=20)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='organizations.branch')),
                ('converted_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_origin', to='members.member')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_visitors_v2', to='members.member')),
            ],
            options={
                'db_table': 'visitors_visitor',
            },
        ),
        migrations.CreateModel(
            name='VisitorFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('CALL', 'Phone Call'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('VISIT', 'In-Person Visit'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('REACHED', 'Reached'), ('NO_RESPONSE', 'No Response'), ('NOT_INTERESTED', 'Not Interested')], default='PENDING', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='visitors.visitor')),
            ],
            options={
                'db_table': 'visitors_follow_up',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['branch', 'status'], name='visitors_vi_branch__0e5bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorfollowup',
            index=models.Index(fields=['visitor', 'outcome'], name='visitors_fo_visitor_6d9d2e_idx'),
        ),
    ]
