# Generated by Django 5.0.14 on 2026-08-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorfollowup',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Stamped by apps.visitors.tasks.send_pending_follow_up_reminders the first (and only) time a reminder notification is sent for this follow-up, so a periodic beat task never reminds the same follow-up twice.', null=True),
        ),
    ]
