# Generated by Django 5.0.14 on 2026-08-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastoralcase',
            options={'ordering': ['-created_at']},
        ),
    ]
