# Generated by Django 5.0.14 on 2026-09-04 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_engagementmetrics_memberfollowup'),
        ('organizations', '0001_initial'),
        ('pastoral', '0002_alter_pastoralcase_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pastoralcase',
            name='closure_reason',
            field=models.TextField(blank=True, help_text='Reason for closing the case'),
        ),
        migrations.AddField(
            model_name='pastoralcase',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who created the case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pastoral_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastoralcase',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text='When case was escalated', null=True),
        ),
        migrations.AddField(
            model_name='pastoralcase',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='Who escalated the case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastoralcase',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Reason for escalation'),
        ),
        migrations.AddField(
            model_name='pastoralcase',
            name='next_follow_up_date',
            field=models.DateField(blank=True, help_text='Date for next scheduled follow-up', null=True),
        ),
        migrations.AddField(
            model_name='pastoralcase',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Case priority for triage', max_length=10),
        ),
        migrations.AddField(
            model_name='pastoralcase',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Who last updated the case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pastoralcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Pastoral staff member assigned to this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastoral_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pastoralcase',
            name='category',
            field=models.CharField(blank=True, help_text='Case category (e.g., Family, Health, Financial, Spiritual)', max_length=100),
        ),
        migrations.AlterField(
            model_name='pastoralcase',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When case was closed', null=True),
        ),
        migrations.AlterField(
            model_name='pastoralcase',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('FOLLOW_UP', 'Follow-Up Needed'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current case status', max_length=15),
        ),
        migrations.AlterField(
            model_name='pastoralcase',
            name='summary',
            field=models.TextField(help_text='Case summary (visible to authorized pastoral staff only)'),
        ),
        migrations.AlterField(
            model_name='pastoralnote',
            name='author',
            field=models.ForeignKey(help_text='Pastoral staff member who wrote this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pastoralnote',
            name='note',
            field=models.TextField(help_text='Pastoral note content (highly sensitive)'),
        ),
        migrations.AddIndex(
            model_name='pastoralcase',
            index=models.Index(fields=['assigned_to', 'status'], name='pastoral_ca_assigne_af77c8_idx'),
        ),
        migrations.AddIndex(
            model_name='pastoralcase',
            index=models.Index(fields=['member', 'status'], name='pastoral_ca_member__7406a1_idx'),
        ),
        migrations.AddIndex(
            model_name='pastoralcase',
            index=models.Index(fields=['priority', 'status'], name='pastoral_ca_priorit_dbade0_idx'),
        ),
        migrations.AddIndex(
            model_name='pastoralcase',
            index=models.Index(fields=['next_follow_up_date'], name='pastoral_ca_next_fo_fb844a_idx'),
        ),
        migrations.AddIndex(
            model_name='pastoralnote',
            index=models.Index(fields=['case', '-created_at'], name='pastoral_no_case_id_e8115f_idx'),
        ),
    ]
