# Generated by Django 5.0.14 on 2026-08-22 14:33

import apps.members.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('other_names', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('photo_url', models.URLField(blank=True)),
                ('membership_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('membership_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='organizations.branch')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='households.household')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members_member',
            },
        ),
        migrations.CreateModel(
            name='MemberQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.members.models._generate_qr_token, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='members.member')),
            ],
            options={
                'db_table': 'members_qr_code',
            },
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased'), ('PENDING', 'Pending')], max_length=20)),
                ('new_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased'), ('PENDING', 'Pending')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='members.member')),
                ('new_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.branch')),
                ('previous_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.branch')),
            ],
            options={
                'db_table': 'members_membership_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='members.member')),
            ],
            options={
                'db_table': 'members_tag',
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['branch', 'membership_status'], name='members_mem_branch__41170b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='members_mem_last_na_92a910_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membertag',
            unique_together={('member', 'label')},
        ),
    ]
