# Generated by Django 5.0.14 on 2026-08-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_options'),
        ('ministries', '0003_alter_group_group_type'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='university.college'),
        ),
        migrations.AddField(
            model_name='member',
            name='community',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('STAFF', 'Staff Community')], help_text='Student or Staff Community. A classification, not a role — see CommunityClassification.', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='university.department'),
        ),
        migrations.AddField(
            model_name='member',
            name='fellowship',
            field=models.ForeignKey(blank=True, help_text='A member has at most one Fellowship (spec section 2). Units/Ministries are many-to-many via GroupMembership.', limit_choices_to={'group_type': 'FELLOWSHIP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fellowship_members', to='ministries.group'),
        ),
    ]
