# Generated by Django 5.0.14 on 2026-09-04 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_college_member_community_member_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementMetrics',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='engagement_metrics', serialize=False, to='members.member')),
                ('services_attended_30d', models.IntegerField(default=0, help_text='Services attended in last 30 days')),
                ('services_attended_90d', models.IntegerField(default=0, help_text='Services attended in last 90 days')),
                ('last_service_date', models.DateField(blank=True, help_text='Date of most recent service attendance', null=True)),
                ('attendance_rate_30d', models.DecimalField(decimal_places=2, default=0, help_text='Attendance rate in last 30 days (0-100%)', max_digits=5)),
                ('events_attended_30d', models.IntegerField(default=0, help_text='Events attended in last 30 days')),
                ('events_attended_90d', models.IntegerField(default=0, help_text='Events attended in last 90 days')),
                ('last_event_date', models.DateField(blank=True, help_text='Date of most recent event attendance', null=True)),
                ('volunteer_assignments_active', models.IntegerField(default=0, help_text='Currently active volunteer assignments')),
                ('volunteer_assignments_completed', models.IntegerField(default=0, help_text='Total volunteer assignments completed (all time)')),
                ('last_volunteer_date', models.DateField(blank=True, help_text='Date of most recent volunteer activity', null=True)),
                ('giving_count_30d', models.IntegerField(default=0, help_text='Number of gifts in last 30 days')),
                ('giving_count_90d', models.IntegerField(default=0, help_text='Number of gifts in last 90 days')),
                ('last_giving_date', models.DateField(blank=True, help_text='Date of most recent giving', null=True)),
                ('engagement_score', models.IntegerField(default=0, help_text='Overall engagement score (0-100)')),
                ('days_since_last_activity', models.IntegerField(default=0, help_text='Days since any recorded activity')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, help_text='When metrics were last calculated')),
            ],
            options={
                'db_table': 'members_engagement_metrics',
                'indexes': [models.Index(fields=['engagement_score'], name='members_eng_engagem_afd80a_idx'), models.Index(fields=['days_since_last_activity'], name='members_eng_days_si_b3b561_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone', models.CharField(choices=[('DAY_7', '7-Day Follow-Up'), ('DAY_30', '30-Day Follow-Up'), ('DAY_90', '90-Day Follow-Up')], help_text='Which follow-up milestone (7/30/90 days)', max_length=10)),
                ('scheduled_for', models.DateTimeField(help_text='When this follow-up is due')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When follow-up was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Follow-up notes (what was discussed, next steps)')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='When reminder was sent. Prevents duplicate reminders (idempotency).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to complete this follow-up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_follow_up_assignments', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='Member being followed up', on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='members.member')),
            ],
            options={
                'db_table': 'members_follow_up',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['scheduled_for', 'completed_at'], name='members_fol_schedul_961a16_idx'), models.Index(fields=['assigned_to', 'completed_at'], name='members_fol_assigne_222d07_idx'), models.Index(fields=['reminder_sent_at'], name='members_fol_reminde_28dfe7_idx')],
                'unique_together': {('member', 'milestone')},
            },
        ),
    ]
