# Generated by Django 5.2.17 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_engagementmetrics_memberfollowup"),
    ]

    operations = [
        migrations.CreateModel(
            name="JupebStudent",
            fields=[],
            options={
                "verbose_name": "JUPEB student",
                "verbose_name_plural": "JUPEB students",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.member",),
        ),
        migrations.CreateModel(
            name="Level100Student",
            fields=[],
            options={
                "verbose_name": "100 Level student",
                "verbose_name_plural": "100 Level students",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.member",),
        ),
        migrations.CreateModel(
            name="Level200Student",
            fields=[],
            options={
                "verbose_name": "200 Level student",
                "verbose_name_plural": "200 Level students",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.member",),
        ),
        migrations.CreateModel(
            name="Level300Student",
            fields=[],
            options={
                "verbose_name": "300 Level student",
                "verbose_name_plural": "300 Level students",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.member",),
        ),
        migrations.CreateModel(
            name="Level400Student",
            fields=[],
            options={
                "verbose_name": "400 Level student",
                "verbose_name_plural": "400 Level students",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.member",),
        ),
        migrations.CreateModel(
            name="Level500Student",
            fields=[],
            options={
                "verbose_name": "500 Level student",
                "verbose_name_plural": "500 Level students",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.member",),
        ),
        migrations.CreateModel(
            name="Level600Student",
            fields=[],
            options={
                "verbose_name": "600 Level student",
                "verbose_name_plural": "600 Level students",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.member",),
        ),
        migrations.AddField(
            model_name="member",
            name="academic_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("JUPEB", "JUPEB"),
                    ("100", "100 Level"),
                    ("200", "200 Level"),
                    ("300", "300 Level"),
                    ("400", "400 Level"),
                    ("500", "500 Level"),
                    ("600", "600 Level"),
                ],
                db_index=True,
                help_text="Required for students; not applicable to staff community members.",
                max_length=5,
            ),
        ),
    ]
