# Generated by Django 5.2.17 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_jupebstudent_level100student_level200student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="community",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STUDENT", "Student"),
                    ("STAFF", "Staff Community"),
                    ("GUEST", "Guest"),
                ],
                help_text="Student or Staff Community. A classification, not a role — see CommunityClassification.",
                max_length=10,
            ),
        ),
    ]
