# Generated by Django 5.0.14 on 2026-08-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name']},
        ),
    ]
