# Generated by Django 5.0.14 on 2026-08-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginhistory_identifier_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CHAPEL_ADMIN', 'Chapel Admin'), ('CHAPLAIN', 'Chaplain'), ('PASTOR', 'Pastor'), ('FINANCE_OFFICER', 'Finance Officer'), ('FELLOWSHIP_LEADER', 'Fellowship Leader'), ('COMMUNITY_LEADER', 'Community Leader'), ('MINISTRY_LEADER', 'Ministry Leader'), ('DEPARTMENT_LEADER', 'Department Leader'), ('UNIT_LEADER', 'Unit Leader'), ('VOLUNTEER', 'Volunteer'), ('MEMBER', 'Member'), ('VISITOR', 'Visitor')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CHAPEL_ADMIN', 'Chapel Admin'), ('CHAPLAIN', 'Chaplain'), ('PASTOR', 'Pastor'), ('FINANCE_OFFICER', 'Finance Officer'), ('FELLOWSHIP_LEADER', 'Fellowship Leader'), ('COMMUNITY_LEADER', 'Community Leader'), ('MINISTRY_LEADER', 'Ministry Leader'), ('DEPARTMENT_LEADER', 'Department Leader'), ('UNIT_LEADER', 'Unit Leader'), ('VOLUNTEER', 'Volunteer'), ('MEMBER', 'Member'), ('VISITOR', 'Visitor')], db_index=True, default='MEMBER', max_length=32),
        ),
    ]
