# Generated by Django 5.0.14 on 2026-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_rolepermission_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CHAPLAIN', 'Chaplain'), ('CHAPEL_ADMIN', 'Chapel Admin'), ('FELLOWSHIP_LEADER', 'Fellowship Leader'), ('UNIT_HEAD', 'Unit Head'), ('MINISTRY_GROUP_LEADER', 'Ministry/Group Leader'), ('MEMBER', 'Member'), ('VISITOR', 'Visitor'), ('PASTOR', 'Pastor (legacy)'), ('FINANCE_OFFICER', 'Finance Officer (legacy)'), ('COMMUNITY_LEADER', 'Community Leader (legacy)'), ('MINISTRY_LEADER', 'Ministry Leader (legacy)'), ('DEPARTMENT_LEADER', 'Department Leader (legacy)'), ('UNIT_LEADER', 'Unit Leader (legacy)'), ('VOLUNTEER', 'Volunteer (legacy)')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CHAPLAIN', 'Chaplain'), ('CHAPEL_ADMIN', 'Chapel Admin'), ('FELLOWSHIP_LEADER', 'Fellowship Leader'), ('UNIT_HEAD', 'Unit Head'), ('MINISTRY_GROUP_LEADER', 'Ministry/Group Leader'), ('MEMBER', 'Member'), ('VISITOR', 'Visitor'), ('PASTOR', 'Pastor (legacy)'), ('FINANCE_OFFICER', 'Finance Officer (legacy)'), ('COMMUNITY_LEADER', 'Community Leader (legacy)'), ('MINISTRY_LEADER', 'Ministry Leader (legacy)'), ('DEPARTMENT_LEADER', 'Department Leader (legacy)'), ('UNIT_LEADER', 'Unit Leader (legacy)'), ('VOLUNTEER', 'Volunteer (legacy)')], db_index=True, default='MEMBER', max_length=32),
        ),
    ]
