# Generated by Django 5.0.14 on 2026-09-04 06:13

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phase3_add_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['module', 'code']},
        ),
        migrations.RenameIndex(
            model_name='roleassignmenthistory',
            new_name='accounts_ro_user_id_3f1b15_idx',
            old_name='accounts_ro_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='accounts_ro_role_ob_fbaa08_idx',
            old_name='accounts_ro_role_ob_idx',
        ),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='accounts_ro_legacy__db7a25_idx',
            old_name='accounts_ro_legacy__idx',
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 4, 6, 13, 46, 708541, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 4, 6, 13, 46, 709288, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
