# Generated by Django 5.2.17 on 2026-09-18 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


INITIAL_PAGES = {
    "home": ("A chapel community for every part of university life", "Join us as we worship, grow, and serve together at Chrisland University Chapel, Abeokuta."),
    "about": ("A community rooted in faith and service", "Chrisland University Chapel serves students and staff through worship, care, formation, and service."),
    "events": ("Events and gatherings", "Find worship services, fellowships, and campus gatherings."),
    "giving": ("Give with purpose", "Support approved chapel programmes through the institution's configured giving channels."),
    "mission": ("Grounded in faith. Prepared for service", "Our mission is to cultivate Christ-centred lives through worship, discipleship, fellowship, and service."),
    "leadership": ("Serving with wisdom and care", "Meet the pastoral and student leaders supporting the chapel community."),
    "services": ("Make room for worship in your week", "Find the chapel's approved worship and prayer gathering information."),
    "contact": ("We are here to listen and help", "Contact the chapel office or plan a visit to the Abeokuta campus."),
    "faq": ("Helpful answers before you arrive", "Answers about chapel services, student participation, attendance, and ChapelFlow."),
}


def seed_initial_pages(apps, schema_editor):
    Branch = apps.get_model("organizations", "Branch")
    ContentEntry = apps.get_model("operations", "ContentEntry")
    now = timezone.now()
    for branch in Branch.objects.filter(is_active=True, branch_type="CHAPEL"):
        for slug, (title, body) in INITIAL_PAGES.items():
            ContentEntry.objects.get_or_create(
                branch=branch,
                slug=slug,
                defaults={
                    "content_type": "PAGE",
                    "title": title,
                    "summary": body,
                    "details": body,
                    "status": "PUBLISHED",
                    "published_at": now,
                    "metadata": {"seeded_initial_page": True},
                },
            )


def remove_initial_pages(apps, schema_editor):
    ContentEntry = apps.get_model("operations", "ContentEntry")
    ContentEntry.objects.filter(metadata__seeded_initial_page=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'operations_content_revision',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='contententry',
            name='author_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='contententry',
            name='content_type',
            field=models.CharField(choices=[('PAGE', 'Website page'), ('NEWS', 'News article'), ('SERMON', 'Sermon'), ('SERMON_SERIES', 'Sermon series'), ('GALLERY', 'Gallery album'), ('GALLERY_IMAGE', 'Gallery image'), ('LIVESTREAM', 'Livestream'), ('MEDIA', 'Media resource')], default='PAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='contententry',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contententry',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contententry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contententry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='operations.contententry'),
        ),
        migrations.AddField(
            model_name='contententry',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contententry',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contententry',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contententry',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contententry',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contententry',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contententry',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('REJECTED', 'Changes requested'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contententry',
            index=models.Index(fields=['branch', 'content_type', 'status'], name='operations__branch__fa32ba_idx'),
        ),
        migrations.AddIndex(
            model_name='contententry',
            index=models.Index(fields=['status', 'publish_at'], name='operations__status_7828ab_idx'),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='operations.contententry'),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.UniqueConstraint(fields=('content', 'version'), name='unique_content_revision_version'),
        ),
        migrations.RunPython(seed_initial_pages, remove_initial_pages),
    ]
