# Generated by Django 5.2.17 on 2026-09-18 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_contentrevision_contententry_author_name_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('details', models.TextField(blank=True)),
                ('due_at', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operations_asset_maintenance',
                'ordering': ['status', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('ISSUE', 'Issue'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Stock adjustment'), ('MAINTENANCE_START', 'Send to maintenance'), ('MAINTENANCE_COMPLETE', 'Complete maintenance')], max_length=24)),
                ('quantity_change', models.IntegerField(default=0)),
                ('quantity_after', models.PositiveIntegerField()),
                ('custodian_name', models.CharField(blank=True, max_length=180)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'operations_asset_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=12),
        ),
        migrations.AddField(
            model_name='asset',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='custodian_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_maintenance_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_maintenance_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity_on_hand',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='tracking_mode',
            field=models.CharField(choices=[('SERIALIZED', 'Individual asset'), ('STOCK', 'Stock item')], default='SERIALIZED', max_length=12),
        ),
        migrations.AddField(
            model_name='asset',
            name='unit_of_measure',
            field=models.CharField(default='item', max_length=30),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('MAINTENANCE', 'In maintenance'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_asset_category',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='operations.assetcategory'),
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_asset_location',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='operations.assetlocation'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__5b4236_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['branch', 'tracking_mode', 'quantity_on_hand'], name='operations__branch__2ed387_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['next_maintenance_at'], name='operations__next_ma_ccecf8_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('asset_tag', ''), _negated=True), fields=('branch', 'asset_tag'), name='unique_asset_tag_per_branch'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='operations.asset'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_asset_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='operations.asset'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_movements_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='operations.assetlocation'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_asset_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='operations.assetlocation'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_asset_category_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='assetlocation',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_asset_location_per_branch'),
        ),
        migrations.AddIndex(
            model_name='assetmaintenance',
            index=models.Index(fields=['asset', 'status', 'due_at'], name='operations__asset_i_cb88d0_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmovement',
            index=models.Index(fields=['asset', '-created_at'], name='operations__asset_i_93bf92_idx'),
        ),
    ]
