# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("operations", "0004_seed_chapel_protocol_unit")]

    operations = [
        migrations.AlterField(
            model_name="contententry",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("PAGE", "Website page"),
                    ("NEWS", "News article"),
                    ("SERMON", "Sermon"),
                    ("SERMON_SERIES", "Sermon series"),
                    ("GALLERY", "Gallery album"),
                    ("GALLERY_IMAGE", "Gallery image"),
                    ("GALLERY_VIDEO", "Gallery video"),
                    ("LIVESTREAM", "Livestream"),
                    ("MEDIA", "Media resource"),
                ],
                default="PAGE",
                max_length=20,
            ),
        ),
    ]
