# Generated by Django 5.2.17 on 2026-09-21 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_contenttype_gallery_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='homepage', max_length=40, unique=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_homepage_content',
            },
        ),
        migrations.CreateModel(
            name='HomepageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('EVENT', 'Event registration / RSVP'), ('UNIT', 'Unit join request')], max_length=10)),
                ('item_id', models.CharField(max_length=64)),
                ('item_title', models.CharField(blank=True, max_length=180)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('matric_no', models.CharField(blank=True, max_length=40)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CLOSED', 'Closed')], default='NEW', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operations_homepage_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'item_id'], name='operations__kind_fbcf2d_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'item_id', 'email'), name='unique_homepage_request_per_email')],
            },
        ),
    ]
