# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("uploads", "0002_alter_upload_category")]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="category",
            field=models.CharField(
                choices=[
                    ("MEMBER_PHOTO", "Member Photo"),
                    ("BRANCH_LOGO", "Branch Logo"),
                    ("EVENT_IMAGE", "Event Image"),
                    ("DOCUMENT", "Document"),
                    ("SERMON_AUDIO", "Sermon Audio"),
                    ("MEDIA_CONTENT", "Published media content"),
                    ("SOCIAL_POST", "Upper Room community post"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
