# Generated by Django 5.2.17 on 2026-09-20

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
        ("uploads", "0003_uploadcategory_social_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("caption", models.CharField(blank=True, max_length=1000)),
                ("status", models.CharField(choices=[("PUBLISHED", "Published"), ("REMOVED", "Removed")], default="PUBLISHED", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="upper_room_posts", to=settings.AUTH_USER_MODEL)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="upper_room_posts", to="organizations.branch")),
            ],
            options={"db_table": "social_post", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SocialReaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="social.socialpost")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="upper_room_likes", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "social_reaction"},
        ),
        migrations.CreateModel(
            name="SocialPostMedia",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("media_type", models.CharField(choices=[("IMAGE", "Image"), ("VIDEO", "Video")], max_length=8)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media", to="social.socialpost")),
                ("upload", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="upper_room_media", to="uploads.upload")),
            ],
            options={"db_table": "social_post_media", "ordering": ["position", "id"]},
        ),
        migrations.CreateModel(
            name="SocialComment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("body", models.CharField(max_length=750)),
                ("status", models.CharField(choices=[("PUBLISHED", "Published"), ("REMOVED", "Removed")], default="PUBLISHED", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="upper_room_comments", to=settings.AUTH_USER_MODEL)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="social.socialpost")),
            ],
            options={"db_table": "social_comment", "ordering": ["created_at"]},
        ),
        migrations.AddIndex(model_name="socialpost", index=models.Index(fields=["branch", "status", "created_at"], name="social_post_branch_status_created_idx")),
        migrations.AddConstraint(model_name="socialreaction", constraint=models.UniqueConstraint(fields=("post", "user"), name="social_one_like_per_user")),
        migrations.AddConstraint(model_name="socialpostmedia", constraint=models.UniqueConstraint(fields=("post", "position"), name="social_post_media_position_unique")),
        migrations.AddIndex(model_name="socialcomment", index=models.Index(fields=["post", "status", "created_at"], name="social_comment_post_status_created_idx")),
    ]
