# Generated by Django 5.0.14 on 2026-08-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='source_announcement',
            field=models.ForeignKey(blank=True, help_text='Set when this notification was fanned out from a communications.Announcement, so delivery state can be tracked/aggregated per-campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='communications.announcement'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('STUBBED', 'Stubbed (provider not configured)')], default='PENDING', max_length=10),
        ),
    ]
