# Generated by Django 5.0.14 on 2026-08-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='members.member'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.eventschedule'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.eventschedule'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtype'),
        ),
        migrations.AddField(
            model_name='location',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.location'),
        ),
        migrations.AddIndex(
            model_name='eventschedule',
            index=models.Index(fields=['event', 'occurrence_start'], name='events_sche_event_i_3ff016_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventschedule',
            unique_together={('event', 'occurrence_start')},
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('schedule', 'member')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['branch', 'start_time'], name='events_even_branch__d4358e_idx'),
        ),
    ]
