# Generated by Django 5.0.14 on 2026-08-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('members', '0003_member_college_member_community_member_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Spec Phase 7: registration deadline. If set, no new registration (CONFIRMED or WAITLISTED) is accepted after this moment.', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=10),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['schedule', 'status'], name='events_regi_schedul_5f7108_idx'),
        ),
    ]
