# Generated by Django 5.0.14 on 2026-08-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('events', '0001_initial'),
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='members.member'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='event_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='events.eventschedule'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='checkindevice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='attendance.checkindevice'),
        ),
        migrations.AddField(
            model_name='visitorattendance',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_visitors', to='members.member'),
        ),
        migrations.AddField(
            model_name='visitorattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='attendance.visitorattendance'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['branch', 'is_open'], name='attendance__branch__792d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'member'], name='attendance__session_077c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['checked_in_at'], name='attendance__checked_c4a9d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('session', 'member'), name='unique_member_per_session'),
        ),
    ]
