# Generated by Django 5.0.14 on 2026-08-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorattendance',
            name='visitor_record',
            field=models.ForeignKey(blank=True, help_text='Link to the full Visitor/first-timer domain record (apps.visitors), added in Phase 0. Nullable so existing rows created before this link existed remain valid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='visitors.visitor'),
        ),
    ]
