# Generated by Django 5.0.14 on 2026-08-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_visitorattendance_visitor_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-checked_in_at']},
        ),
        migrations.AlterModelOptions(
            name='visitorattendance',
            options={'ordering': ['-checked_in_at']},
        ),
    ]
