# Generated by Django 5.0.14 on 2026-08-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_phase1_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkindevice',
            name='secret_hash',
            field=models.CharField(blank=True, help_text='Hashed (never plaintext) per-device credential, set via CheckInDeviceViewSet.rotate_secret. Required for kiosk check-in (see KioskCheckInView) -- a device with no secret set cannot check anyone in.', max_length=255),
        ),
    ]
