# Generated by Django 5.0.14 on 2026-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_checkindevice_secret_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='Optional check-out time for duration tracking. Must be >= checked_in_at.', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', help_text="Server-determined status: PRESENT (on-time), LATE (after grace period), ABSENT (didn't check in), EXCUSED (administratively approved absence)", max_length=10),
        ),
    ]
