# Generated by Django 5.0.14 on 2026-09-07 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_checked_out_at_and_more'),
        ('members', '0004_engagementmetrics_memberfollowup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='OPEN', max_length=12),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='window_closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='window_opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='attendance.attendancesession')),
                ('usher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_checkpoint',
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='attendance.attendancecheckpoint'),
        ),
        migrations.CreateModel(
            name='AttendanceScanAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_reference', models.CharField(blank=True, max_length=64)),
                ('result', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_attempts', to='attendance.attendancecheckpoint')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_attempts', to='attendance.attendancesession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_scan_attempts', to='members.member')),
            ],
            options={
                'db_table': 'attendance_scan_attempt',
            },
        ),
        migrations.AddIndex(
            model_name='attendancecheckpoint',
            index=models.Index(fields=['session', 'usher'], name='attendance__session_e827dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancecheckpoint',
            constraint=models.UniqueConstraint(fields=('session', 'usher'), name='unique_usher_checkpoint_per_session'),
        ),
        migrations.AddIndex(
            model_name='attendancescanattempt',
            index=models.Index(fields=['session', '-created_at'], name='attendance__session_472e58_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancescanattempt',
            index=models.Index(fields=['student', '-created_at'], name='attendance__student_5cf2aa_idx'),
        ),
    ]
