# Generated by Django 5.0.14 on 2026-08-22 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_by_name', models.CharField(blank=True, help_text='For anonymous/visitor submissions.', max_length=255)),
                ('category', models.CharField(choices=[('HEALING', 'Healing'), ('FAMILY', 'Family'), ('FINANCIAL', 'Financial'), ('SPIRITUAL', 'Spiritual Growth'), ('THANKSGIVING', 'Thanksgiving'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('details', models.TextField()),
                ('is_private', models.BooleanField(default=True, help_text='If true, only pastoral staff and assignee can view.')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ANSWERED', 'Answered'), ('CLOSED', 'Closed')], default='NEW', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prayer_requests', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='organizations.branch')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to='members.member')),
            ],
            options={
                'db_table': 'prayer_request',
            },
        ),
        migrations.CreateModel(
            name='PrayerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='prayer.prayerrequest')),
            ],
            options={
                'db_table': 'prayer_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['branch', 'status'], name='prayer_requ_branch__6e3bfd_idx'),
        ),
    ]
