# Generated by Django 5.0.14 on 2026-09-04 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_engagementmetrics_memberfollowup'),
        ('organizations', '0001_initial'),
        ('prayer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='answered_at',
            field=models.DateTimeField(blank=True, help_text='When prayer was answered', null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='closure_reason',
            field=models.TextField(blank=True, help_text="Reason for closing (e.g., 'Answered', 'Request withdrawn', 'No longer applicable')"),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the request (for staff-entered requests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prayer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='privacy_level',
            field=models.CharField(choices=[('PRIVATE', 'Private (Requester + Assigned Staff Only)'), ('PASTORAL', 'Pastoral Staff Only'), ('FELLOWSHIP', 'Fellowship Leaders + Pastoral'), ('PUBLIC', 'Public (All Branch Members)')], default='PRIVATE', help_text='Who can view this prayer request', max_length=15),
        ),
        migrations.AlterField(
            model_name='prayernote',
            name='author',
            field=models.ForeignKey(help_text='Staff member who wrote this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prayernote',
            name='note',
            field=models.TextField(help_text='Follow-up note content'),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to pray/follow-up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prayer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='details',
            field=models.TextField(help_text='Prayer request details'),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Legacy field: If true, only pastoral staff and assignee can view (deprecated, use privacy_level)'),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Member submitting the request (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to='members.member'),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('FOLLOW_UP', 'Follow-Up Needed'), ('ANSWERED', 'Answered'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=15),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='submitted_by_name',
            field=models.CharField(blank=True, help_text='For anonymous/visitor submissions', max_length=255),
        ),
        migrations.AddIndex(
            model_name='prayernote',
            index=models.Index(fields=['prayer_request', '-created_at'], name='prayer_note_prayer__fa3742_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='prayer_requ_assigne_19657d_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['member', 'status'], name='prayer_requ_member__a247ad_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['privacy_level', 'branch'], name='prayer_requ_privacy_9970d6_idx'),
        ),
    ]
