# Generated by Django 5.0.14 on 2026-08-22 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('LEADER', 'Leader'), ('ASSISTANT_LEADER', 'Assistant Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'groups_membership',
            },
        ),
    ]
