# Generated by Django 5.0.14 on 2026-08-22 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('MINISTRY', 'Ministry'), ('FELLOWSHIP', 'Fellowship'), ('DEPARTMENT', 'Department'), ('UNIT', 'Unit'), ('SMALL_GROUP', 'Small Group')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='organizations.branch')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='members.member')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ministries.group')),
            ],
            options={
                'db_table': 'ministries_group',
                'indexes': [models.Index(fields=['branch', 'group_type'], name='ministries__branch__525398_idx')],
            },
        ),
    ]
