# Generated by Django 5.0.14 on 2026-08-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('MINISTRY', 'Ministry'), ('FELLOWSHIP', 'Fellowship'), ('COMMUNITY', 'Community'), ('DEPARTMENT', 'Department'), ('UNIT', 'Unit'), ('SMALL_GROUP', 'Small Group')], max_length=20),
        ),
    ]
