# Generated by Django 5.0.14 on 2026-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0002_alter_group_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('MINISTRY', 'Ministry'), ('FELLOWSHIP', 'Fellowship'), ('UNIT', 'Unit'), ('SMALL_GROUP', 'Small Group'), ('COMMUNITY', 'Community (legacy)'), ('DEPARTMENT', 'Department (legacy — do not use, see apps.university)')], max_length=20),
        ),
    ]
