# Generated by Django 5.0.14 on 2026-08-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_college_member_community_member_department_and_more'),
        ('ministries', '0003_alter_group_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED (Phase 0 remediation): kept only for backward compatibility with existing data/reports. Do not read this for scoping or new leadership listings — a Group can have multiple leaders, and this single FK cannot represent that. Use active groups.GroupMembership rows with role=LEADER instead (see common.permissions.scoping.led_group_ids and docs/university_structure.md). The column is intentionally NOT dropped yet — see that doc for the removal plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='members.member'),
        ),
    ]
