# Generated by Django 5.0.14 on 2026-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_engagementmetrics_memberfollowup'),
        ('ministries', '0004_alter_group_leader'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('branch', 'name', 'group_type'), name='unique_group_name_per_branch_type'),
        ),
    ]
